const express = require("express")
const app = express()
app.use("/css",express.static("./css"))
app.use("/images",express.static("./images"))
app.use("/js",express.static("./js"))
app.use("/",express.static("./html"))
app.listen(8080)
